language: node_js
node_js:
  - "node"
  - "6"
  - "8"
sudo: required
addons:
  chrome: stable 
cache:
  directories:
    - "node_modules"
install: npm install -g npx && npx lerna bootstrap  
script: npx lerna run test
